version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Current directory structure:"
      - find . -print
      - echo "Gradle version:"
      - ./gradlew --version
  build:
    commands:
      - echo "Starting build"
      - chmod +x ./gradlew
      - ./gradlew clean build --info --stacktrace
  post_build:
    commands:
      - echo "Build completed"
      - echo "Build directory contents:"
      - find build -print

artifacts:
  files:
    - build/libs/*.jar
  discard-paths: yes
