# Application
spring.application.name=2NY
# base URL
app.base-url=http://localhost:8080
# Server
server.port=8080
server.error.whitelabel.enabled=false

# Database
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/2ny?serverTimezone=Asia/Seoul
spring.datasource.username=
spring.datasource.password=2ny

# Logging
logging.level.org.springframework=info
logging.level.com.mega._NY=debug
logging.level.org.springframework.security=info

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.apache.http=DEBUG
logging.level.httpclient.wire=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG

server.servlet.encoding.force-response=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# ??? ??? ?? ??
test.image.thumbnail=static/images/default_Thumbnail.png
test.image.description=static/images/default_descriptionImage.png


